sudo: false
language: node_js
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
install:
- npm install
deploy:
  provider: gae
  project: payment-services
  keyfile: client-secret.json
  skip_cleanup: true
  default: true
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_f8010e12ef19_key -iv $encrypted_f8010e12ef19_iv
  -in client-secret.json.enc -out client-secret.json -d
