sudo: false
language: node_js
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_32e8b768a5e8_key -iv $encrypted_32e8b768a5e8_iv
  -in client-secret.json.enc -out client-secret.json -d
install:
- npm install
deploy:
  provider: gae
  project: payment-services
  keyfile: client-secret.json
  skip_cleanup: true
  default: true
  on:
    all_branches: true
