runtime: nodejs
env: flex

endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud service-management deploy openapi.yaml' command.
  name: echo-api.endpoints.payment-services.cloud.goog
  config_id: 2018-NN-DDxx

env_variables:
  PAGSEG_CLIENT_EMAIL: 'XXXXXXXXXXXXXXa@gmail.com'
  PAGSEG_CLIENT_TOKEN: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  PAGSEG_URL: 'https://ws.pagseguro.uol.com.br/v2/checkout'
